fine_wine_n_dine/urls.py
"""
fine_wine_n_dine URL Configuration
 
"""
from django.contrib import admin
from django.urls import path, include
from reviews import views
from bookings import views
from site_pages import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('sign_up/', include('site_pages.urls'), name='sign_up'),
    path('reviews/', include('reviews.urls'), name='reviews'),
    path('bookings/', include('bookings.urls'), name='bookings'),
    path('accounts/', include('allauth.urls')),    
    path('', include('site_pages.urls'), name='home'),
        
]

reviews/urls.py
"""
    imports  ------Bookings urls.py----------------------
"""
# third party imports
from django.urls import path
# internal imports
from . import views

urlpatterns = [
    path(
        'reviews/reviews/',
        views.ReviewsList.as_view(),
        name='reviews'
        ),

    path(
        'reviews/create_review/',
        views.CreateReview.as_view(),
        name='create_review'
        ),
    path(
        'reviews/like/<slug:slug>/',
        views.ReviewLike.as_view(),
        name='review_like'
        ),
    path(
        'reviews/edit_review/<int:pk>/',
        views.EditReview.as_view(),
        name='edit_review'
        ),
    path(
        'reviews/delete_review/<int:pk>/',
        views.DeleteReview.as_view(),
        name='delete_review'
        ),
    path(
        'reviews/edit_comment/<int:pk>/',
        views.EditComment.as_view(),
        name='edit_comment'
        ),
    path(
        'reviews/delete_comment/<int:pk>/',
        views.DeleteComment.as_view(),
        name='delete_comment'
        ),
    path(
        'reviews/<slug:slug>/',
        views.ReviewsDetail.as_view(),
        name='review_details'
        ),
]

reviews/models.py
"""
    imports  -----------------reviews models.py----------------------
"""
# third party imports
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.shortcuts import reverse

from cloudinary.models import CloudinaryField

STATUS = (
    (0, 'Draft'),
    (1, 'Published')
    )


class Review(models.Model):
    """
        Class based model for Reviews
    """
    title = models.CharField(max_length=200, unique=True)

    slug = models.SlugField(max_length=200, unique=True)

    author = models.ForeignKey(
        User, on_delete=models.CASCADE,
        related_name='review_posts'
        )

    updated_on = models.DateTimeField(auto_now=True)

    content = models.TextField()

    featured_image = CloudinaryField(
        'image',
        default='placeholder'
        )

    excerpt = models.TextField(blank=True)

    created_on = models.DateTimeField(auto_now_add=True)

    status = models.IntegerField(choices=STATUS, default=0)

    likes = models.ManyToManyField(
        User,
        related_name='review_likes',
        blank=True
        )

    class Meta:
        """
            meta class to set the order in which
            the reviews are displayed
        """
        ordering = ['-created_on']

    def get_absolute_url(self):
        """
            function to define the reverse URL
            for after a review is created or edited
        """
        return reverse('reviews')

    def save(self, *args, **kwargs):
        """
            function to edit and save the slug
            for after a review is created or edited
        """
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        """
            function to return the review title as a string
        """
        return str(self.title)

    def number_of_likes(self):
        """
            function to return the number of likes on a review
        """
        return self.likes.count()


class Comment(models.Model):
    """
        Class based model for Comments
    """

    post = models.ForeignKey(
        Review,
        on_delete=models.CASCADE,
        related_name='comments'
        )

    name = models.CharField(max_length=80)

    email = models.EmailField()

    body = models.TextField()

    created_on = models.DateTimeField(auto_now_add=True)

    approved = models.BooleanField(default=False)

    class Meta:
        """
            meta class to set the order in which
            the reviews are displayed
        """
        ordering = ['created_on']

    def __str__(self):
        """
            function to return the commentbody and the author as a string
        """
        return f"Comment {self.body} by {self.name}"

    def get_absolute_url(self):
        """
            function to define the reverse URL
            for after a comment is created or edited
        """
        return reverse('reviews')

reviews/forms.py
"""
    imports  -------------Reviews forms.py----------------------
"""
# third party imports
from django import forms
# internal imports
from .models import Comment, Review


class CommentForm(forms.ModelForm):
    """
    Class based form to create new comments using the
    comments model
    """
    class Meta:
        """
        Class to indicate which model to use and to
        set the fields in the create comment model form
        """
        model = Comment
        fields = ('body',)


class CreateReviewForm(forms.ModelForm):
    """
        Class based form to set the fields in
        the Create Review model form for creating a new review
    """
    class Meta:
        """
        Class to indicate which model to use and to
        set the fields in the create review model form
        """
        model = Review
        fields = (
            'title',
            'content',
            'featured_image',
            'excerpt'
            )

reviews/views.py
"""
    imports  ------Reviews views.py----------------------
"""
# third party imports
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic, View
from django.template.defaultfilters import slugify
from django.views.generic import TemplateView, UpdateView, DeleteView
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
# internal imports
from .models import Review, Comment
from .forms import CommentForm, CreateReviewForm


class ReviewsList(generic.ListView):
    """
        Class based view to display all reviews
    """
    model = Review
    queryset = Review.objects.filter(status=1).order_by('-created_on')
    template_name = 'reviews/reviews.html'
    paginate_by = 9


class CreateReview(TemplateView):
    """
        Class based view to render create reviews page
        with CreateReviewForm to create new reviews, GET request
        data from user and process POST request accordingly
    """
    template_name = 'reviews/create_review.html'

    def get(self, request, *args, **kwargs):
        """
        GET request for rendering the create review
        page including the CreateReviewForm
        """
        form = CreateReviewForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        """
        POST request for processing the CreateReviewForm
        data passed from the create review page and if
        form is valid saves booking to database.
        """
        form = CreateReviewForm(request.POST)
        if form.is_valid():
            form.instance.author = request.user
            title = form.cleaned_data['title']
            form.instance.slug = slugify(title)
            content = form.cleaned_data['content']
            featured_image = form.cleaned_data['featured_image']
            excerpt = form.cleaned_data['excerpt']
            review = form.save(commit=False)
            review.post = review
            review.save()
        else:
            form = CreateReviewForm()
            return render(request, self.template_name, {'form': form})

        return HttpResponseRedirect(reverse('reviews'))


class EditReview(UpdateView):
    """
        Class based view to display edit booking
        page with booking form relative to the
        current selected booking and utilising
        the built in django updateview for saving
        updated data to the database.
    """
    model = Review
    template_name = 'reviews/edit_review.html'
    fields = [
        'title',
        'content',
        'featured_image',
        'excerpt',
        ]


class DeleteReview(DeleteView):
    """
        Class based view to delete the selected
        review using the built in Django Deleteview.
    """
    model = Review
    template_name = 'reviews/delete_review.html'
    success_url = reverse_lazy('reviews')


class ReviewsDetail(View):
    """
        Class based view to display the selected
        reviews specific details and comments.
    """
    template_name = "reviews/reviews_detail.html"

    def get(self, request, slug):
        """
        class based function to render the reviews detail page
        diaplaying the review details for the selected review
        and renders the commentform and displays all comments
        related to the specific review.
        """
        queryset = Review.objects.filter(status=1)
        review = get_object_or_404(queryset, slug=slug)
        comments = review.comments.filter(approved=True).order_by('created_on')
        liked = False
        if review.likes.filter(id=self.request.user.id).exists():
            liked = True

        return render(
            request,
            self.template_name,
            {
                "review": review,
                "comments": comments,
                "commented": False,
                "liked": liked,
                'comment_form': CommentForm(),
            },
        )

    def post(self, request, slug):
        """
        POST request for processing the CommentForm
        data passed from the reviews details page and if
        form is valid saves comment to database.
        """
        queryset = Review.objects.filter(status=1)
        review = get_object_or_404(queryset, slug=slug)
        comments = review.comments.filter(approved=True).order_by('created_on')
        liked = False
        if review.likes.filter(id=self.request.user.id).exists():
            liked = True

        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            comment_form.instance.email = request.user.email
            comment_form.instance.name = request.user.username
            comment = comment_form.save(commit=False)
            comment.post = review
            comment.save()

        else:
            comment_form = CommentForm()

        return render(
            request,
            "reviews/reviews_detail.html",
            {
                "review": review,
                "comments": comments,
                "commented": True,
                "liked": liked,
                'comment_form': CommentForm(),
            },
        )


class EditComment(UpdateView):
    """
        Class based view to display edit comment
        page with comment form relative to the
        current selected review and utilising
        the built in django updateview for saving
        updated data to the database.
    """
    model = Comment
    template_name = 'reviews/edit_comment.html'
    fields = [
        'body',
        ]


class DeleteComment(DeleteView):
    """
        Class based view to delete the selected
        comment using the built in Django Deleteview.
    """
    model = Comment
    template_name = 'reviews/delete_comment.html'
    success_url = reverse_lazy('reviews')


class ReviewLike(View):
    """
        Class based view to toggle the liked status for
        the selected comment and saving to the database.
    """
    def post(self, request, slug):
        """
        POST request for processing the review liked status
        data passed from the reviews details page and if
        form is valid updates and saves status to database.
        """
        post = get_object_or_404(Review, slug=slug)
        if post.likes.filter(id=request.user.id).exists():
            post.likes.remove(request.user)
        else:
            post.likes.add(request.user)
        return HttpResponseRedirect(reverse('review_details', args=[slug]))

templates/reviews/create_review.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}


<section class="page-section cta">
  <div class="container">
     <div class="row">
      <div class="col-xl-9 mx-auto">
        <div class="cta-inner bg-faded text-center rounded">
            
            {% if new_review %}
            <h2 id="msg">Thank you for your review, your review will be published shortly. </h2>
            <div>
              <h2>Review Content</h2>
                  <h3> Review Title:  {{ title }}</h3>
                  <h3> Review Content:  {{ content }}</h3>
                  <h3> Review {{ featured_image }}</h3>
                  <h3> 4 {{ excerpt }}</h3>
                  <h3> 5 user id = {{ user.id }}</h3>
                  <h3>6 {{ new_review }}</h3>
              </div> 
            {% else %}
            <h2>Create a Review:</h2>
            <form  method="POST" style="margin-top: 1.3em;">  
                          
                {{ form | crispy }}
                
                {% csrf_token %}
                
                  <button type="submit" class="btn btn-primary btn-xl" >Submit</button> 
                
                              
            </form> 
            {% endif %}   

            
            
            
        </div>
      </div>
    </div>
  </div>
</section>









    {% endblock %}

templates/reviews/delete_comment.html
{% extends "base.html" %}


{% block content %}
<section class="page-section cta">
  <div class="container">
     <div class="row"> 
      <div class="col-xl-9 mx-auto">
        <div class="cta-inner bg-faded text-center rounded">
            <h2>Delete Comment: {{comment.body}}</h2>
            <h2>Created by: {{comment.name}}</h2>
            <br>
            <hr>
            <form  method="POST" style="margin-top: 1.3em;">                 
                {% csrf_token %}
                <hr>
                <strong>Are You Sure You Want To DELETE this comment?</strong>
                <hr>
                <button type="submit" class="btn btn-primary btn-xl red" >DELETE COMMENT !</button> 
            </form> 
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/reviews/delete_review.html
{% extends "base.html" %}


{% block content %}
<section class="page-section cta">
  <div class="container">
     <div class="row"> 
      <div class="col-xl-9 mx-auto">
        <div class="cta-inner bg-faded text-center rounded">
            <h2>Delete Review: {{ review.title }}</h2>
            <h2>Review Author: {{ review.author }}</h2>
            <br>
            <hr>
            <form  method="POST" style="margin-top: 1.3em;">                 
                {% csrf_token %}
                <hr>
                <strong>Are You Sure You Want To DELETE this review?</strong>
                <hr>
                <button type="submit" class="btn btn-primary btn-xl red" >DELETE REVIEW !</button> 
            </form> 
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/reviews/edit_comment.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}


<section class="page-section cta">
  <div class="container">
     <div class="row">  
      <div class="col-xl-9 mx-auto">
        <div class="cta-inner bg-faded text-center rounded">
                    
          <h2>Update Comment:</h2>
          <form  method="POST" style="margin-top: 1.3em;">  
                        
              {{ form | crispy }}
              
              {% csrf_token %}
              
              <button type="submit" class="btn btn-primary btn-xl" >UPDATE COMMENT</button> 
          </form>   
        </div>
      </div>
    </div>
  </div>
</section>









    {% endblock %}

templates/reviews/edit_review.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}


<section class="page-section cta">
  <div class="container">
     <div class="row">
      <div class="col-xl-9 mx-auto">
        <div class="cta-inner bg-faded text-center rounded">
          
            <h2>Update Review:</h2>
            <form  method="POST" style="margin-top: 1.3em;">  
                          
                {{ form | crispy }}
                
                {% csrf_token %}
                
                <button type="submit" class="btn btn-primary btn-xl" >UPDATE</button> 
                
                              
            </form> 
             

            
            
            
        </div>
      </div>
    </div>
  </div>
</section>









    {% endblock %}

templates/reviews/reviews.html
{% extends "base.html" %}


{% block content %}
{% if user.is_authenticated %}
<nav class="navbar navbar-expand-lg navbar-dark py-lg-4 mainNav">
    <div class="container">            
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <hr>
            <ul class="navbar-nav mx-auto">                
                <li class="nav-item px-lg-4">
                    <a class="nav-link text-uppercase" href="{% url 'create_review' %}">Create Review</a>
                </li>                
            </ul>
        </div>
    </div>
</nav>
{% else %}                
{% endif %}

<div class="container-fluid ">
    <div class="row ">
        <div class="col-12 mt-3 left">
            <div class="row centre-cards centre-cards-margin">
            {% for review in review_list %}                       
                <div class="col-md-4">
                    <div class="card mb-4 ml-6 card-width-sml">
                        <a href="{% url 'review_details' review.slug %}">
                            <div class="card-body ">
                                <div class="image-container">                                
                                   {% if "placeholder" in review.featured_image.url %}
                                    <img class="card-img-top"
                                        src="/static/images/food-critic.jpg">
                                    
                                    {% else %}
                                    <img class="card-img-top" src=" {{ review.featured_image.url }}" alt="image related to review {{ review.title }}">
                                    {% endif %}
                                    <div class="image-flash">
                                        <p class="author">Author: {{ review.author }}</p>
                                    </div> 
                                                               
                                </div>
                                
                                <h2 class="card-title">{{ review.title }}</h2>
                                <p class="card-text">{{ review.excerpt }}</p>
                                
                                
                                <hr />
                                <p class="card-text text-muted h6">{{ review.created_on}} <i class="far fa-heart"></i>
                                    {{ review.number_of_likes }}
                                </p>
                            </div>
                        </a> 
                    </div>
                </div>


            {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row centre-cards centre-cards-margin">
            {% endif %}

            {% endfor%}

            </div>
        </div>
    </div>


    {% if is_paginated %}
    <nav aria-label="Page navigation">        
        <ul class="pagination justify-content-center">
			{% if page_obj.has_previous %}
			<li class="intro-button mx-auto"><a href="?page={{ page_obj.previous_page_number }}" class="page-link btn btn-primary btn-xl">&laquo; PREV </a></li>
			{% endif %}
			{% if page_obj.has_next %}
			<li class="intro-button mx-auto"><a href="?page={{ page_obj.next_page_number }}" class="page-link btn btn-primary btn-xl"> NEXT &raquo;</a></li>
			{% endif %}
		</ul>
    </nav>
    {% endif %}
</div>


{% endblock content%}

templates/reviews/reviews_detail.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}

{% load crispy_forms_tags %}

<div class="container ">
    <div class="row">
        <div class="col-md-8 offset-md-2 my-3">
            {% if commented %}
            <div class="alert alert-success success-dismissible fade show" id="msg" role="alert">
                Thank you {{ user.username }}, your comment has been submitted for approval
                <button type="button" class="btn-close float-end" data-bs-dismiss="success" aria-label="Close"></button>                
            </div>  
            {% endif %}   
        </div>
    </div>
</div>


<div class="col-xl-7 mx-auto">
    <div class="masthead">
        <div class="container">
            <div class="row g-0 centre-cards ">
                <div class="col-md-6 masthead-text">
                    <h1 class="post-title ">
                        {{ review.title }}
                    </h1>
                    <p class="post-subtitle ">{{ review.author }} | {{ review.created_on }}</p>                
                </div>
                <div class="d-md-block col-md-6 masthead-image reviews-detail">
                    {% if "placeholder" in review.featured_image.url %}
                    <img src="{% static 'images/food-critic.jpg' %}" alt="No image supplied and placeholder image used of cartoon food critic">
                    {% else %}
                    <img src="{{ review.featured_image.url }}" alt="image related to review {{ review.title }}">
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row reviews-detail">
            <div class="col card mb-4  mt-3 left  top wooden-back">
                <div class="card-body">
                    <p class="card-text white"> {{ review.content | safe }}</p>
                    <div class="row">
                        <div class="col-1">
                            <strong>
                                {% if user.is_authenticated %}
                                    <form class="d-inline like-btn-outline" action="{% url 'review_like' review.slug %}" method="POST">
                                        {% csrf_token %}
                                        {% if liked %}
                                            <button type="submit" name="reviewpost_id" value="{{ review.slug }}" class="btn-like wooden-back like-btn-outline" id="like-btn">
                                                <i class="fas fa-heart red"></i>
                                            </button>

                                        {% else %}
                                            <button type="submit" name="reviewpost_id" value="{{ review.slug }}" class="btn-like wooden-back like-btn-outline" >
                                                <i class="far fa-heart white"></i>
                                            </button>
                                        {% endif %}    
                                    </form>
                                {% else %}
                                    <span class="text-secondary"> <i class="far fa-heart white"></i> </span>                                
                                {% endif %}
                                <span class="text-secondary">{{ review.number_of_likes }}</span>
                            </strong>                        
                        </div>
                        <div class="col-1">
                            {% with comments.count as total_comments %}
                            <strong class="text-secondary"><i class="far fa-comments"></i>
                                {{ total_comments}}
                            </strong>
                            {% endwith %}
                        </div>
                        {% if review.author == request.user %}
                        <div>
                            <div class="intro-button mx-auto"><a class="btn btn-primary btn-xl" href="{% url 'edit_review' review.pk %}">EDIT REVIEW</a></div>
                            <div class="intro-button mx-auto"><a class="btn btn-primary btn-xl red" href="{% url 'delete_review' review.pk %}">DELETE REVIEW</a></div>
                        </div>
                        {% endif %}
                    </div>
                </div>                           
            </div>
        </div>
        <div class="row">
            <div class="col">
                <hr>
            </div>
        </div>
        <div class="row ">
            <div class="col-md-8 card mb-4  mt-3 reviews-detail centre-text wooden-back">
                <h4 >Comments:</h4>
                <div class="card-body">
                    {% for comment in comments %}
                    <div class="comments wooden-back white" style="padding: 10px;">
                        <p class="font-weight-bold">
                            {{ comment.name }}
                            <span class=" text-highlighted font-weight-bold wooden-back ">
                                {{ comment.created_on }}
                            </span> wrote:
                        </p>
                        {{ comment.body  | linebreaks }}
                    </div>
                    <div>
                        {% if comment.name == user.username %}
                        <div>
                            <div class="intro-button mx-auto"><a class="btn btn-primary btn-xl" href="{% url 'edit_comment' comment.pk %}">EDIT COMMENT</a></div>
                            <div class="intro-button mx-auto"><a class="btn btn-primary btn-xl red" href="{% url 'delete_comment' comment.pk %}">DELETE COMMENT</a></div>
                        </div>             
                        {% endif %}  
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-4 card mb-4  mt-3 wooden-back">
                <div >
                    {% if commented %}
                    <div class="card-body min-20">
                        <div class="alert alert-success" role="alert" id="msg">
                    Your comment is awaiting approval
                        </div>
                    </div>                
                    {% else %}
                    {% if user.is_authenticated %}
                    <div class="min-20">
                        <h4 class="wooden-back" >Leave a comment:</h4>
                        <div class="card-body ">
                            <p>Posting as: {{ user.username }}</p>
                            <form method="post" style="margin-top: 1.3em;">
                                {{ comment_form | crispy }}
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary btn-xl" >Submit</button>                    
                            </form>
                        </div>
                    </div>    
                    {% endif %}
                    {% endif %}                
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}